# Generated by Django 3.1.3 on 2020-12-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.IntegerField(blank=True, choices=[(1, 'America'), (2, 'Germany'), (3, 'Australia'), (4, 'France')], null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bidders',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.IntegerField(blank=True, choices=[(1, 'America'), (2, 'Germany'), (3, 'Australia'), (4, 'France')], null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
